### ISSUE TITLE
Client Crash upon loading into multiplayer server, MC 1.20.1

### ISSUE THREAD

**Issue by Twigstick71** [DAQEM/Arc#4]
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 2023-11-08 11:54:14
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "com.daqem.arc.api.action.holder.IActionHolder.getActions()" because "actionHolder" is null
	at com.daqem.arc.api.action.data.ActionData.lambda$getPlayerActions$0(ActionData.java:75) ~[arc-1.3.2-forge.jar%23428!/:?] {re:mixin,re:classloading}
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273) ~[?:?] {}
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?] {}
	at com.daqem.arc.api.action.data.ActionData.getPlayerActions(ActionData.java:76) ~[arc-1.3.2-forge.jar%23428!/:?] {re:mixin,re:classloading}
	at com.daqem.arc.api.action.data.ActionData.sendToAction(ActionData.java:54) ~[arc-1.3.2-forge.jar%23428!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.entity.player.Player.handler$ben000$getCurrentItemAttackStrengthDelay(Player.java:3243) ~[client-1.20.1-20230612.114412-srg.jar%23666!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_playerentity_iswearing,xf:fml:xaeroworldmap:xaero_wm_playerentity_iswearing,re:computing_frames,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_playerentity_iswearing,xf:fml:xaeroworldmap:xaero_wm_playerentity_iswearing,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_playerentity_iswearing,xf:fml:xaeroworldmap:xaero_wm_playerentity_iswearing,pl:mixin:APP:playerAnimator-common.mixins.json:PlayerEntityMixin,pl:mixin:APP:supplementaries.mixins.json:PlayerProjectileMixin,pl:mixin:APP:arc-common.mixins.json:common.MixinPlayer,pl:mixin:APP:mixins.cobblemon-common.json:PlayerMixin,pl:mixin:APP:attributeslib.mixins.json:PlayerMixin,pl:mixin:APP:mixins.adorn.forge.json:PlayerEntityMixin,pl:mixin:APP:the_bumblezone-common.mixins.json:entities.PlayerMixin,pl:mixin:APP:the_bumblezone-common.mixins.json:items.HoneyShieldPlayerMixin,pl:mixin:APP:the_bumblezone-common.mixins.json:items.PlayerDamageShieldInvoker,pl:mixin:APP:puffish_skills.mixins.json:PlayerEntityMixin,pl:mixin:APP:ars_nouveau.mixins.json:elytra.ElytraPlayerMixin,pl:mixin:APP:canary.mixins.json:calc.if_else.entity.handle_entity_event.player.PlayerMixin,pl:mixin:APP:canary.mixins.json:calc.if_else.player_slot.PlayerMixin,pl:mixin:APP:blue_skies.mixins.json:PlayerEntityMixin,pl:mixin:APP:aether.mixins.json:common.PlayerMixin,pl:mixin:APP:aether.mixins.json:common.accessor.PlayerAccessor,pl:mixin:APP:bygonenether.mixins.json:NoAxeDisableModShieldMixin,pl:mixin:APP:biomemakeover-common.mixins.json:PlayerMixin,pl:mixin:APP:comforts.mixins.json:AccessorPlayer,pl:mixin:APP:expandability-common.mixins.json:swimming.PlayerMixin,pl:mixin:APP:kubejs-common.mixins.json:PlayerMixin,pl:mixin:A}
	at net.minecraft.world.entity.player.Player.m_36333_(Player.java:1932) ~[client-1.20.1-20230612.114412-srg.jar%23666!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_playerentity_iswearing,xf:fml:xaeroworldmap:xaero_wm_playerentity_iswearing,re:computing_frames,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_playerentity_iswearing,xf:fml:xaeroworldmap:xaero_wm_playerentity_iswearing,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_playerentity_iswearing,xf:fml:xaeroworldmap:xaero_wm_playerentity_iswearing,pl:mixin:APP:playerAnimator-common.mixins.json:PlayerEntityMixin,pl:mixin:APP:supplementaries.mixins.json:PlayerProjectileMixin,pl:mixin:APP:arc-common.mixins.json:common.MixinPlayer,pl:mixin:APP:mixins.cobblemon-common.json:PlayerMixin,pl:mixin:APP:attributeslib.mixins.json:PlayerMixin,pl:mixin:APP:mixins.adorn.forge.json:PlayerEntityMixin,pl:mixin:APP:the_bumblezone-common.mixins.json:entities.PlayerMixin,pl:mixin:APP:the_bumblezone-common.mixins.json:items.HoneyShieldPlayerMixin,pl:mixin:APP:the_bumblezone-common.mixins.json:items.PlayerDamageShieldInvoker,pl:mixin:APP:puffish_skills.mixins.json:PlayerEntityMixin,pl:mixin:APP:ars_nouveau.mixins.json:elytra.ElytraPlayerMixin,pl:mixin:APP:canary.mixins.json:calc.if_else.entity.handle_entity_event.player.PlayerMixin,pl:mixin:APP:canary.mixins.json:calc.if_else.player_slot.PlayerMixin,pl:mixin:APP:blue_skies.mixins.json:PlayerEntityMixin,pl:mixin:APP:aether.mixins.json:common.PlayerMixin,pl:mixin:APP:aether.mixins.json:common.accessor.PlayerAccessor,pl:mixin:APP:bygonenether.mixins.json:NoAxeDisableModShieldMixin,pl:mixin:APP:biomemakeover-common.mixins.json:PlayerMixin,pl:mixin:APP:comforts.mixins.json:AccessorPlayer,pl:mixin:APP:expandability-common.mixins.json:swimming.PlayerMixin,pl:mixin:APP:kubejs-common.mixins.json:PlayerMixin,pl:mixin:A}
	at net.minecraft.world.entity.player.Player.m_36403_(Player.java:1936) ~[client-1.20.1-20230612.114412-srg.jar%23666!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_playerentity_iswearing,xf:fml:xaeroworldmap:xaero_wm_playerentity_iswearing,re:computing_frames,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_playerentity_iswearing,xf:fml:xaeroworldmap:xaero_wm_playerentity_iswearing,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_playerentity_iswearing,xf:fml:xaeroworldmap:xaero_wm_playerentity_iswearing,pl:mixin:APP:playerAnimator-common.mixins.json:PlayerEntityMixin,pl:mixin:APP:supplementaries.mixins.json:PlayerProjectileMixin,pl:mixin:APP:arc-common.mixins.json:common.MixinPlayer,pl:mixin:APP:mixins.cobblemon-common.json:PlayerMixin,pl:mixin:APP:attributeslib.mixins.json:PlayerMixin,pl:mixin:APP:mixins.adorn.forge.json:PlayerEntityMixin,pl:mixin:APP:the_bumblezone-common.mixins.json:entities.PlayerMixin,pl:mixin:APP:the_bumblezone-common.mixins.json:items.HoneyShieldPlayerMixin,pl:mixin:APP:the_bumblezone-common.mixins.json:items.PlayerDamageShieldInvoker,pl:mixin:APP:puffish_skills.mixins.json:PlayerEntityMixin,pl:mixin:APP:ars_nouveau.mixins.json:elytra.ElytraPlayerMixin,pl:mixin:APP:canary.mixins.json:calc.if_else.entity.handle_entity_event.player.PlayerMixin,pl:mixin:APP:canary.mixins.json:calc.if_else.player_slot.PlayerMixin,pl:mixin:APP:blue_skies.mixins.json:PlayerEntityMixin,pl:mixin:APP:aether.mixins.json:common.PlayerMixin,pl:mixin:APP:aether.mixins.json:common.accessor.PlayerAccessor,pl:mixin:APP:bygonenether.mixins.json:NoAxeDisableModShieldMixin,pl:mixin:APP:biomemakeover-common.mixins.json:PlayerMixin,pl:mixin:APP:comforts.mixins.json:AccessorPlayer,pl:mixin:APP:expandability-common.mixins.json:swimming.PlayerMixin,pl:mixin:APP:kubejs-common.mixins.json:PlayerMixin,pl:mixin:A}
	at net.minecraft.client.renderer.ItemInHandRenderer.m_109311_(ItemInHandRenderer.java:522) ~[client-1.20.1-20230612.114412-srg.jar%23666!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:renderdata,xf:fml:twilightforest:render,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:renderdata,xf:fml:twilightforest:render,pl:mixin:APP:playerAnimator-common.mixins.json:firstPerson.ItemInHandRendererMixin,pl:mixin:APP:aether.mixins.json:client.accessor.ItemInHandRendererAccessor,pl:mixin:APP:alexscaves.mixins.json:client.ItemInHandRendererMixin,pl:mixin:APP:moonlight-common.mixins.json:FirstPersonRendererMixin,pl:mixin:APP:taniwha-common.mixins.json:item.animation.ItemInHandRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109148_(GameRenderer.java:652) ~[client-1.20.1-20230612.114412-srg.jar%23666!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:supplementaries-common.mixins.json:GameRendererMixin,pl:mixin:APP:rubidium.mixins.json:features.gui.hooks.console.GameRendererMixin,pl:mixin:APP:mixins.cobblemon-common.json:GameRendererMixin,pl:mixin:APP:fastload.mixins.json:client.GameRendererMixin,pl:mixin:APP:ars_nouveau.mixins.json:GameRendererMixin,pl:mixin:APP:forge-immediatelyfast-common.mixins.json:core.compat.MixinGameRenderer,pl:mixin:APP:alexscaves.mixins.json:client.GameRendererMixin,pl:mixin:APP:justzoom.mixin.json:MixinGameRenderer,pl:mixin:APP:create.mixins.json:accessor.GameRendererAccessor,pl:mixin:APP:create.mixins.json:client.GameRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1804) ~[client-1.20.1-20230612.114412-srg.jar%23666!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1112) ~[client-1.20.1-20230612.114412-srg.jar%23666!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23666!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[client-1.20.1.jar:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:flywheel.mixins.json:ClientMainMixin,pl:mixin:APP:smoothboot.mixins.json:client.MainMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.1.46.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.1.46.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.1.46.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

**Comment by DAQEM** [comment]
What version of the mod are you using?

**Comment by Twigstick71** [comment]
arc 1.3.2 forge 
jobs+ remastered 1.2.4

**Comment by ltpbro** [comment]
im getting the error aswell have to load into a single player map then i can join a multiplayer server

using arc-1.3.2-forge, jobsplus-1.2.3-forge

[crash-2023-11-09_04.48.15-client.txt](https://github.com/DAQEM/Arc/files/13300644/crash-2023-11-09_04.48.15-client.txt)

**Comment by DAQEM** [comment]
517b30788461cc4ef8485fb745421bbd881644b3 has fixed this issue. New jar will be uploaded asap
